spring:
  application:
    name: CLINVIO-DISCOVERY-SERVER

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${clinvio.discovery.server.hostname}:${server.port}/eureka/