spring:
  application:
    name: CLINVIO-DISCOVERY-SERVER

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${clinvio.discovery.server.hostname}:${server.port}/eureka/